services:
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
      target: data
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    container_name: qotd-deck-bot
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    stdin_open: true
    tty: true
    depends_on:
      migrations:
        condition: service_completed_successfully